"""Emotion System 的集中参数。"""


ALLOWED_EMOTIONS = {"neutral", "happy", "curious", "surprised"}

EMOTION_DECAY_SECONDS = 30.0
EMOTION_NEUTRAL_THRESHOLD = 0.10
EMOTION_UPDATE_INTERVAL = 1.0

OLD_EMOTION_WEIGHT = 0.35
NEW_EMOTION_WEIGHT = 0.65
SPEECH_AROUSAL_BOOST = 0.05

RELATIONSHIP_MULTIPLIERS = {
    "stranger": 0.85,
    "acquaintance": 1.0,
    "friend": 1.15,
}

NPC_STATE_INTENSITY_SYNC_THRESHOLD = 0.05
NPC_STATE_HEARTBEAT_SECONDS = 5.0
