"""Dynamic Emotion State 的集中、确定性参数。"""


BASELINE_VALENCE = 0.20
BASELINE_AROUSAL = 0.30
BASELINE_SOCIAL_COMFORT = 0.40
BASELINE_CURIOSITY = 0.50

EMOTION_DECAY_STEP = 0.05
EMOTION_UPDATE_INTERVAL = 1.0

NPC_STATE_INTENSITY_SYNC_THRESHOLD = 0.05
NPC_STATE_HEARTBEAT_SECONDS = 5.0
