"""Spatial Perception 的集中配置参数。"""

# 通用关键点与空间位置参数。
LANDMARK_VISIBILITY_THRESHOLD = 0.5
POSITION_ENTER_LEFT = 0.38
POSITION_EXIT_LEFT = 0.43
POSITION_ENTER_RIGHT = 0.62
POSITION_EXIT_RIGHT = 0.57
DISTANCE_ENTER_NEAR = 0.32
DISTANCE_EXIT_NEAR = 0.28
DISTANCE_ENTER_FAR = 0.14
DISTANCE_EXIT_FAR = 0.18

# Pose 关键点回退使用的粗略二维头向阈值。
POSE_HEAD_YAW_RATIO_THRESHOLD = 0.12
POSE_HEAD_UP_HEIGHT_RATIO = 1.25
POSE_HEAD_DOWN_HEIGHT_RATIO = 0.80

# 离散状态需要连续多少帧一致，才正式切换。
PRESENCE_CONFIRM_FRAMES = 3
FACE_CONFIRM_FRAMES = 3
POSITION_CONFIRM_FRAMES = 4
DISTANCE_CONFIRM_FRAMES = 4
HAND_CONFIRM_FRAMES = 3
HEAD_CONFIRM_FRAMES = 4
LOOKING_CONFIRM_FRAMES = 3
GAZE_CONFIRM_FRAMES = 3
EYE_CONTACT_CONFIRM_FRAMES = 3

# Head Pose 连续数值的指数移动平均参数。越大越灵敏，越小越平滑。
HEAD_POSE_EMA_ALPHA = 0.25
ATTENTION_EMA_ALPHA = 0.20

# solvePnP 输出方向在不同镜头或坐标约定下可能相反，可在这里校准。
HEAD_POSE_YAW_SIGN = 1.0
HEAD_POSE_PITCH_SIGN = -1.0

# 使用 yaw / pitch 生成兼容 head_direction 的角度阈值。
HEAD_DIRECTION_YAW_DEGREES = 15.0
HEAD_DIRECTION_PITCH_DEGREES = 12.0

# Attention Score 的有效角度范围和稳定时间。
ATTENTION_YAW_MAX_DEGREES = 35.0
ATTENTION_PITCH_MAX_DEGREES = 25.0
ATTENTION_STABILITY_FRAMES = 15

# Attention Score 权重，总和为 1.0。
ATTENTION_WEIGHT_FACE = 0.30
ATTENTION_WEIGHT_YAW = 0.25
ATTENTION_WEIGHT_PITCH = 0.20
ATTENTION_WEIGHT_POSITION = 0.10
ATTENTION_WEIGHT_DISTANCE = 0.05
ATTENTION_WEIGHT_STABILITY = 0.10

# looking_at_npc 迟滞阈值：高于进入阈值才进入，低于退出阈值才退出。
ATTENTION_ENTER_THRESHOLD = 0.75
ATTENTION_EXIT_THRESHOLD = 0.55

# MediaPipe Face Mesh 参数。
FACE_MAX_COUNT = 1
FACE_MIN_DETECTION_CONFIDENCE = 0.5
FACE_MIN_TRACKING_CONFIDENCE = 0.5

# Iris / Gaze 参数。水平符号必须用真实摄像头验证，必要时切换反转开关。
GAZE_INVERT_HORIZONTAL = False
GAZE_INVERT_VERTICAL = False
GAZE_DEFAULT_NEUTRAL_X = 0.5
GAZE_DEFAULT_NEUTRAL_Y = 0.5
GAZE_IRIS_EMA_ALPHA = 0.35
GAZE_SCORE_EMA_ALPHA = 0.30
GAZE_HORIZONTAL_THRESHOLD = 0.10
GAZE_VERTICAL_THRESHOLD = 0.08
GAZE_HORIZONTAL_MAX_OFFSET = 0.28
GAZE_VERTICAL_MAX_OFFSET = 0.20
GAZE_MIN_EYE_WIDTH_PIXELS = 8.0
GAZE_MIN_EYE_HEIGHT_PIXELS = 2.5
GAZE_RELIABLE_EYE_WIDTH_PIXELS = 40.0
GAZE_RELIABLE_EYE_HEIGHT_PIXELS = 10.0
GAZE_MAX_HORIZONTAL_DISAGREEMENT = 0.25
GAZE_MAX_VERTICAL_DISAGREEMENT = 0.30
GAZE_SINGLE_EYE_RELIABILITY_FACTOR = 0.65
GAZE_CALIBRATION_FRAMES = 45

# Gaze Score 权重，总和为 1.0。
GAZE_WEIGHT_HORIZONTAL = 0.35
GAZE_WEIGHT_VERTICAL = 0.30
GAZE_WEIGHT_CONSISTENCY = 0.20
GAZE_WEIGHT_RELIABILITY = 0.15
GAZE_ORIENTATION_GATE_BASE = 0.40

# Eye Contact 由 Head Attention 与 Gaze 共同决定。
EYE_CONTACT_WEIGHT_ATTENTION = 0.45
EYE_CONTACT_WEIGHT_GAZE = 0.55
EYE_CONTACT_ENTER_THRESHOLD = 0.80
EYE_CONTACT_EXIT_THRESHOLD = 0.60

# Python → Unity UDP 参数。
UNITY_IP = "127.0.0.1"
UNITY_PORT = 5052
STATE_HEARTBEAT_SECONDS = 1.0
